# Workflow derived from https://github.com/r-lib/actions/tree/master/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  release:
  workflow_dispatch:

name: Release

jobs:
  release:
    runs-on: ubuntu-latest

    name: Release
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      SHINYAPPS_TOKEN: ${{ secrets.SHINYAPPS_TOKEN }}
      SHINYAPPS_SECRET: ${{ secrets.SHINYAPPS_SECRET }}
      R_KEEP_PKG_SOURCE: yes

    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-pandoc@v2
      - uses: r-lib/actions/setup-r@v2
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: rsconnect
      - uses: r-lib/actions/check-r-package@v2
      - name: Deploy
        run: |
          rsconnect::setAccountInfo(name='surveillance', token='${{ env.SHINYAPPS_TOKEN }}', secret='${{ secrets.SHINYAPPS_SECRET }}')
          rsconnect::deployApp()
        shell: Rscript {0}
